# Generated by Django 6.0.4 on 2026-04-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singleorderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='singleorderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='CartOrders',
        ),
        migrations.DeleteModel(
            name='SingleOrderItem',
        ),
    ]
